services:
  - type: web
    name: math-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.config.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.config.settings
