services:
  - type: web
    name: math-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.config.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.config.settings
      - key: DATABASE_URL
        fromDatabase:
          name: math-mobile-db
          property: connectionString

databases:
  - name: math-mobile-db
    databaseName: math_mobile
    user: math_mobile_user
    plan: free
