# Generated by Django 5.0.4 on 2025-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_folder_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
